const books = [
    {
        id: "1",
        catId: 4,
        title: "Beginning Android Programming",
        author: "J.F DiMarzio",
        authorbio: "About DiMarzio",
        publicationdate: "2017 by John Wiley & Sons",
        introduction: "This book is written to help start beginning Android developers ",
        picture: require("./../assets/images/books/android.png"),
        cost: 25,
        images: [
            require("./../assets/images/books/an1.png"),
            require("./../assets/images/books/an2.jpg"),
            require("./../assets/images/books/an3.jpeg"),
        ],
        colors: [
            "#00BFFF",
            "#FF1493",
            "#00CED1",
            "#228B22",
            "#20B2AA",
            "#FF4500",
        ]
    },
    {
        id: "2",
        catId: 3,
        title: "ES6 & Beyound",
        author: "Kyle Simpson",
        authorbio: "Kyle Simpson is a thorough pragmatist.",
        publicationdate: "2015-5-5",
        introduction: "This book is about shaking up your sense of understanding by exposing you ",
        picture: require("./../assets/images/books/es6.png"),
        cost: 35.99,
        images: [
            require("./../assets/images/books/es1.png"),
            require("./../assets/images/books/es2.jpg"),
            require("./../assets/images/books/es3.png"),
        ],
        colors: [
            "#00BFFF",
            "#FF1493",
            "#00CED1",
            "#228B22",
            "#20B2AA",
            "#FF4500",
        ]
    },
    {
        id: "3",
        catId: 4,
        title: "ng-book 2",
        author: "Ari Lerner",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "A complete refernce book on angular 2. ",
        picture: require("./../assets/images/books/ngbook21.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/ng1.png"),
            require("./../assets/images/books/ng2.jpg"),
            require("./../assets/images/books/ng3.jpg"),
        ],
        colors: null
    },
    {
        id: "4",
        catId: 6,
        title: "Pro Git",
        author: "Scott Chacon and Ben Straub",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Welcome to the second edition of Pro Git.  ",
        picture: require("./../assets/images/books/progit.png"),
        cost: 45.99,
        images: [
            require("./../assets/images/books/pg1.jpeg"),
            require("./../assets/images/books/pg2.jpeg"),
            require("./../assets/images/books/pg3.png"),
        ],
        colors:null
    },
    {
        id: "5",
        catId: 7,
        title: "Reactjs Blueprints",
        author: "Sven A. Robbestad",
        authorbio: "Sven A. Robbestad is a developer with a keen interest in the Web .",
        publicationdate: "2016-7-10",
        introduction: "ReactJS was developed as a tool to solve a problem with the application state. ",
        picture: require("./../assets/images/books/reactjsblue.png"),
        cost: 20.99,
        images: [
            require("./../assets/images/books/rb1.png"),
            require("./../assets/images/books/rb2.jpg"),
            require("./../assets/images/books/rb3.jpeg"),
        ],
        colors: null
    },
    {
        id: "6",
        catId: 8,
        title: "ReAwaken The Giant Within",
        author: "Tony Robins",
        authorbio: "Tony Robbins is one of the great influences of this generation.",
        publicationdate: "2013-5-10",
        introduction: "I’m sending you this gift of a condensed version of my 544-page original book in the hope",
        picture: require("./../assets/images/books/awaken.png"),
        cost: 22,
        images: [
            require("./../assets/images/books/aw1.jpg"),
            require("./../assets/images/books/aw2.jpg"),
            require("./../assets/images/books/aw3.png"),
        ],
        colors: null
    },
    {
        id: "7",
        catId: 10,
        title: "SurviveJS",
        author: "Juho Vapsalainen",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Front-end development moves forward fast.  ",
        picture: require("./../assets/images/books/survivejs.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/sj1.png"),
            require("./../assets/images/books/sj2.jpeg"),
            require("./../assets/images/books/sj3.png"),
        ],
        colors: null
    },
    {
        id: "8",
        catId: 11,
        title: "Switching To Angular2",
        author: "Minko Gechev",
        authorbio: "Minko Gechev is a software engineer who strongly believes in open source software. ",
        publicationdate: "March 2016",
        introduction: "It is the modern framework you need to build performant and robust web applications.",

        picture: require("./../assets/images/books/switchingto.png"),
        cost: 21,
        images: [
            require("./../assets/images/books/sa1.jpeg"),
            require("./../assets/images/books/sa2.jpeg"),
            require("./../assets/images/books/sa3.jpeg"),
        ],
        colors: null
    },
    {
        id: "9",
        catId: 13,
        title: "Unlimited Sales Success",
        author: "Brian Tracy",
        authorbio: "A world class motivational and sales consultant.",
        publicationdate: "2013-2-10",
        introduction: "A complete refernce book on todays selling. ",
        picture: require("./../assets/images/books/selling.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/s1.jpeg"),
            require("./../assets/images/books/s2.jpeg"),
            require("./../assets/images/books/s3.jpeg"),
        ],
        colors: null
    },
    {
        id: "10",
        catId: 14,
        title: "Web Development with Node and ExpressJS",
        author: "Ethan Brown",
        authorbio: "A senior software engineer at PoP Art.",
        publicationdate: "2014-6-27",
        introduction: "Learn to build modern web applications with node and expressjs ",
        picture: require("./../assets/images/books/node.png"),
        cost: 19.99,
        images: [
            require("./../assets/images/books/n1.png"),
            require("./../assets/images/books/n2.jpeg"),
            require("./../assets/images/books/n3.jpeg"),
        ],
        colors: null
    },
    {
        id: "11",
        catId: 15,
        title: "Beginning Android Programming",
        author: "J.F DiMarzio",
        authorbio: "About DiMarzio",
        publicationdate: "2017 by John Wiley & Sons",
        introduction: "This book is written to help start beginning Android developers ",
        picture: require("./../assets/images/books/android.png"),
        cost: 25,
        images: [
            require("./../assets/images/books/an1.png"),
            require("./../assets/images/books/an2.jpg"),
            require("./../assets/images/books/an3.jpeg"),
        ],
        colors: null
    },
    {
        id: "12",
        catId: 17,
        title: "ES6 & Beyound",
        author: "Kyle Simpson",
        authorbio: "Kyle Simpson is a thorough pragmatist.",
        publicationdate: "2015-5-5",
        introduction: "This book is about shaking up your sense of understanding by exposing you ",
        picture: require("./../assets/images/books/es6.png"),
        cost: 35.99,
        images: [
            require("./../assets/images/books/es1.png"),
            require("./../assets/images/books/es2.jpg"),
            require("./../assets/images/books/es3.png"),
        ],
        colors: null
    },
    {
        id: "13",
        catId: 18,
        title: "ng-book 2",
        author: "Ari Lerner",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "A complete refernce book on angular 2. ",
        picture: require("./../assets/images/books/ngbook21.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/ng1.png"),
            require("./../assets/images/books/ng2.jpg"),
            require("./../assets/images/books/ng3.jpg"),
        ],
        colors: null
    },
    {
        id: "14",
        catId: 20,
        title: "Pro Git",
        author: "Scott Chacon and Ben Straub",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Welcome to the second edition of Pro Git.  ",
        picture: require("./../assets/images/books/progit.png"),
        cost: 45.99,
        images: [
            require("./../assets/images/books/pg1.jpeg"),
            require("./../assets/images/books/pg2.jpeg"),
            require("./../assets/images/books/pg3.png"),
        ],
        colors: null
    },
    {
        id: "15",
        catId: 21,
        title: "Reactjs Blueprints",
        author: "Sven A. Robbestad",
        authorbio: "Sven A. Robbestad is a developer with a keen interest in the Web .",
        publicationdate: "2016-7-10",
        introduction: "ReactJS was developed as a tool to solve a problem with the application state. ",
        picture: require("./../assets/images/books/reactjsblue.png"),
        cost: 20.99,
        images: [
            require("./../assets/images/books/rb1.png"),
            require("./../assets/images/books/rb2.jpg"),
            require("./../assets/images/books/rb3.jpeg"),
        ],
        colors: null
    },
    {
        id: "16",
        catId: 22,
        title: "ReAwaken The Giant Within",
        author: "Tony Robins",
        authorbio: "Tony Robbins is one of the great influences of this generation.",
        publicationdate: "2013-5-10",
        introduction: "I’m sending you this gift of a condensed version of my 544-page original book in the hope",
        picture: require("./../assets/images/books/awaken.png"),
        cost: 22,
        images: [
            require("./../assets/images/books/aw1.jpg"),
            require("./../assets/images/books/aw2.jpg"),
            require("./../assets/images/books/aw3.png"),
        ],
        colors: null
    },
    {
        id: "17",
        catId: 24,
        title: "SurviveJS",
        author: "Juho Vapsalainen",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Front-end development moves forward fast.  ",
        picture: require("./../assets/images/books/survivejs.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/sj1.png"),
            require("./../assets/images/books/sj2.jpeg"),
            require("./../assets/images/books/sj3.png"),
        ],
        colors: null
    },
    {
        id: "18",
        catId: 25,
        title: "Switching To Angular2",
        author: "Minko Gechev",
        authorbio: "Minko Gechev is a software engineer who strongly believes in open source software. ",
        publicationdate: "March 2016",
        introduction: "It is the modern framework you need to build performant and robust web applications.",

        picture: require("./../assets/images/books/switchingto.png"),
        cost: 21,
        images: [
            require("./../assets/images/books/sa1.jpeg"),
            require("./../assets/images/books/sa2.jpeg"),
            require("./../assets/images/books/sa3.jpeg"),
        ],
        colors: null
    },
    {
        id: "19",
        catId: 2,
        title: "Unlimited Sales Success",
        author: "Brian Tracy",
        authorbio: "A world class motivational and sales consultant.",
        publicationdate: "2013-2-10",
        introduction: "A complete refernce book on todays selling. ",
        picture: require("./../assets/images/books/selling.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/s1.jpeg"),
            require("./../assets/images/books/s2.jpeg"),
            require("./../assets/images/books/s3.jpeg"),
        ],
        colors: null
    },
    {
        id: "20",
        catId: 3,
        title: "Web Development with Node and ExpressJS",
        author: "Ethan Brown",
        authorbio: "A senior software engineer at PoP Art.",
        publicationdate: "2014-6-27",
        introduction: "Learn to build modern web applications with node and expressjs ",
        picture: require("./../assets/images/books/node.png"),
        cost: 19.99,
        images: [
            require("./../assets/images/books/n1.png"),
            require("./../assets/images/books/n2.jpeg"),
            require("./../assets/images/books/n3.jpeg"),
        ],
        colors: null
    },
    {
        id: "21",
        catId: 4,
        title: "Beginning Android Programming",
        author: "J.F DiMarzio",
        authorbio: "About DiMarzio",
        publicationdate: "2017 by John Wiley & Sons",
        introduction: "This book is written to help start beginning Android developers ",
        picture: require("./../assets/images/books/android.png"),
        cost: 25,
        images: [
            require("./../assets/images/books/an1.png"),
            require("./../assets/images/books/an2.jpg"),
            require("./../assets/images/books/an3.jpeg"),
        ],
        colors: null
    },
    {
        id: "22",
        catId: 6,
        title: "ES6 & Beyound",
        author: "Kyle Simpson",
        authorbio: "Kyle Simpson is a thorough pragmatist.",
        publicationdate: "2015-5-5",
        introduction: "This book is about shaking up your sense of understanding by exposing you ",
        picture: require("./../assets/images/books/es6.png"),
        cost: 35.99,
        images: [
            require("./../assets/images/books/es1.png"),
            require("./../assets/images/books/es2.jpg"),
            require("./../assets/images/books/es3.png"),
        ],
        colors: null
    },
    {
        id: "23",
        catId: 7,
        title: "ng-book 2",
        author: "Ari Lerner",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "A complete refernce book on angular 2. ",
        picture: require("./../assets/images/books/ngbook21.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/ng1.png"),
            require("./../assets/images/books/ng2.jpg"),
            require("./../assets/images/books/ng3.jpg"),
        ],
        colors: null
    },
    {
        id: "24",
        catId: 8,
        title: "Pro Git",
        author: "Scott Chacon and Ben Straub",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Welcome to the second edition of Pro Git.  ",
        picture: require("./../assets/images/books/progit.png"),
        cost: 45.99,
        images: [
            require("./../assets/images/books/pg1.jpeg"),
            require("./../assets/images/books/pg2.jpeg"),
            require("./../assets/images/books/pg3.png"),
        ],
        colors: null
    },
    {
        id: "25",
        catId: 10,
        title: "Reactjs Blueprints",
        author: "Sven A. Robbestad",
        authorbio: "Sven A. Robbestad is a developer with a keen interest in the Web .",
        publicationdate: "2016-7-10",
        introduction: "ReactJS was developed as a tool to solve a problem with the application state. ",
        picture: require("./../assets/images/books/reactjsblue.png"),
        cost: 20.99,
        images: [
            require("./../assets/images/books/rb1.png"),
            require("./../assets/images/books/rb2.jpg"),
            require("./../assets/images/books/rb3.jpeg"),
        ],
        colors: null
    },
    {
        id: "26",
        catId: 11,
        title: "ReAwaken The Giant Within",
        author: "Tony Robins",
        authorbio: "Tony Robbins is one of the great influences of this generation.",
        publicationdate: "2013-5-10",
        introduction: "I’m sending you this gift of a condensed version of my 544-page original book in the hope",
        picture: require("./../assets/images/books/awaken.png"),
        cost: 22,
        images: [
            require("./../assets/images/books/aw1.jpg"),
            require("./../assets/images/books/aw2.jpg"),
            require("./../assets/images/books/aw3.png"),
        ],
        colors: null
    },
    {
        id: "27",
        catId: 12,
        title: "SurviveJS",
        author: "Juho Vapsalainen",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Front-end development moves forward fast.  ",
        picture: require("./../assets/images/books/survivejs.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/sj1.png"),
            require("./../assets/images/books/sj2.jpeg"),
            require("./../assets/images/books/sj3.png"),
        ],
        colors: null
    },
    {
        id: "28",
        catId: 13,
        title: "Switching To Angular2",
        author: "Minko Gechev",
        authorbio: "Minko Gechev is a software engineer who strongly believes in open source software. ",
        publicationdate: "March 2016",
        introduction: "It is the modern framework you need to build performant and robust web applications.",

        picture: require("./../assets/images/books/switchingto.png"),
        cost: 21,
        images: [
            require("./../assets/images/books/sa1.jpeg"),
            require("./../assets/images/books/sa2.jpeg"),
            require("./../assets/images/books/sa3.jpeg"),
        ],
        colors: null
    },
    {
        id: "29",
        catId: 14,
        title: "Unlimited Sales Success",
        author: "Brian Tracy",
        authorbio: "A world class motivational and sales consultant.",
        publicationdate: "2013-2-10",
        introduction: "A complete refernce book on todays selling. ",
        picture: require("./../assets/images/books/selling.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/s1.jpeg"),
            require("./../assets/images/books/s2.jpeg"),
            require("./../assets/images/books/s3.jpeg"),
        ],
        colors: null
    },
    {
        id: "30",
        catId: 17,
        title: "Web Development with Node and ExpressJS",
        author: "Ethan Brown",
        authorbio: "A senior software engineer at PoP Art.",
        publicationdate: "2014-6-27",
        introduction: "Learn to build modern web applications with node and expressjs ",
        picture: require("./../assets/images/books/node.png"),
        cost: 19.99,
        images: [
            require("./../assets/images/books/n1.png"),
            require("./../assets/images/books/n2.jpeg"),
            require("./../assets/images/books/n3.jpeg"),
        ],
        colors: null
    },
    {
        id: "31",
        catId: 18,
        title: "Beginning Android Programming",
        author: "J.F DiMarzio",
        authorbio: "About DiMarzio",
        publicationdate: "2017 by John Wiley & Sons",
        introduction: "This book is written to help start beginning Android developers ",
        picture: require("./../assets/images/books/android.png"),
        cost: 25,
        images: [
            require("./../assets/images/books/an1.png"),
            require("./../assets/images/books/an2.jpg"),
            require("./../assets/images/books/an3.jpeg"),
        ],
        colors: null
    },
    {
        id: "32",
        catId: 20,
        title: "ES6 & Beyound",
        author: "Kyle Simpson",
        authorbio: "Kyle Simpson is a thorough pragmatist.",
        publicationdate: "2015-5-5",
        introduction: "This book is about shaking up your sense of understanding by exposing you ",
        picture: require("./../assets/images/books/es6.png"),
        cost: 35.99,
        images: [
            require("./../assets/images/books/es1.png"),
            require("./../assets/images/books/es2.jpg"),
            require("./../assets/images/books/es3.png"),
        ],
        colors: null
    },
    {
        id: "33",
        catId: 21,
        title: "ng-book 2",
        author: "Ari Lerner",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "A complete refernce book on angular 2. ",
        picture: require("./../assets/images/books/ngbook21.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/ng1.png"),
            require("./../assets/images/books/ng2.jpg"),
            require("./../assets/images/books/ng3.jpg"),
        ],
        colors: null
    },
    {
        id: "34",
        catId: 22,
        title: "Pro Git",
        author: "Scott Chacon and Ben Straub",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Welcome to the second edition of Pro Git.  ",
        picture: require("./../assets/images/books/progit.png"),
        cost: 45.99,
        images: [
            require("./../assets/images/books/pg1.jpeg"),
            require("./../assets/images/books/pg2.jpeg"),
            require("./../assets/images/books/pg3.png"),
        ],
        colors: null
    },
    {
        id: "35",
        catId: 23,
        title: "Reactjs Blueprints",
        author: "Sven A. Robbestad",
        authorbio: "Sven A. Robbestad is a developer with a keen interest in the Web .",
        publicationdate: "2016-7-10",
        introduction: "ReactJS was developed as a tool to solve a problem with the application state. ",
        picture: require("./../assets/images/books/reactjsblue.png"),
        cost: 20.99,
        images: [
            require("./../assets/images/books/rb1.png"),
            require("./../assets/images/books/rb2.jpg"),
            require("./../assets/images/books/rb3.jpeg"),
        ],
        colors: null
    },
    {
        id: "36",
        catId: 24,
        title: "ReAwaken The Giant Within",
        author: "Tony Robins",
        authorbio: "Tony Robbins is one of the great influences of this generation.",
        publicationdate: "2013-5-10",
        introduction: "I’m sending you this gift of a condensed version of my 544-page original book in the hope",
        picture: require("./../assets/images/books/awaken.png"),
        cost: 22,
        images: [
            require("./../assets/images/books/aw1.jpg"),
            require("./../assets/images/books/aw2.jpg"),
            require("./../assets/images/books/aw3.png"),
        ],
        colors: null
    },
    {
        id: "37",
        catId: 25,
        title: "SurviveJS",
        author: "Juho Vapsalainen",
        authorbio: "Full stack web developer and trainer.",
        publicationdate: "2016-5-10",
        introduction: "Front-end development moves forward fast.  ",
        picture: require("./../assets/images/books/survivejs.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/sj1.png"),
            require("./../assets/images/books/sj2.jpeg"),
            require("./../assets/images/books/sj3.png"),
        ],
        colors: null
    },
    {
        id: "38",
        catId: 2,
        title: "Switching To Angular2",
        author: "Minko Gechev",
        authorbio: "Minko Gechev is a software engineer who strongly believes in open source software. ",
        publicationdate: "March 2016",
        introduction: "It is the modern framework you need to build performant and robust web applications.",
        picture: require("./../assets/images/books/switchingto.png"),
        cost: 21,
        images: [
            require("./../assets/images/books/sa1.jpeg"),
            require("./../assets/images/books/sa2.jpeg"),
            require("./../assets/images/books/sa3.jpeg"),
        ],
        colors: null
    },
    {
        id: "39",
        catId: 3,
        title: "Unlimited Sales Success",
        author: "Brian Tracy",
        authorbio: "A world class motivational and sales consultant.",
        publicationdate: "2013-2-10",
        introduction: "A complete refernce book on todays selling. ",
        picture: require("./../assets/images/books/selling.png"),
        cost: 25.99,
        images: [
            require("./../assets/images/books/s1.jpeg"),
            require("./../assets/images/books/s2.jpeg"),
            require("./../assets/images/books/s3.jpeg"),
        ],
        colors: null
    },
    {
        id: "40",
        catId: 4,
        title: "Web Development with Node and ExpressJS",
        author: "Ethan Brown",
        authorbio: "A senior software engineer at PoP Art.",
        publicationdate: "2014-6-27",
        introduction: "Learn to build modern web applications with node and expressjs ",
        picture: require("./../assets/images/books/node.png"),
        cost: 19.99,
        images: [
            require("./../assets/images/books/n1.png"),
            require("./../assets/images/books/n2.jpeg"),
            require("./../assets/images/books/n3.jpeg"),
        ],
        colors: null
    }
];

export const getProducts = () => {
    return books;

}

